version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "13:00"
      timezone: "Asia/Kolkata"
    assignees:
      - "vipiny35"
    reviewers:
      - "vipiny35"
    labels:
      - "update"
    target-branch: "main"
