openapi: 3.0.0
info:
  title: prism-api
  description: |-
    # prisma-api swagger docs
  version: 1.0.0
servers:
  - url: /
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - ADMIN
            - USER
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
tags:
  - name: User
paths:
  /user/:
    post:
      tags:
        - User
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
              example:
                name: John
                email: doe@example.com
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    get:
      tags:
        - User
      summary: Get All Users
      responses:
        "200":
          description: Successful response
          content:
            application/json: 
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /user/{userId}:
    get:
      tags:
        - User
      summary: Get One User
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    patch:
      tags:
        - User
      summary: Update User
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
              example:
                name: Max
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - User
      summary: Delete User
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to delete
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  